on:
  push:
    branches:
      - main
      - develop

name: Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v6

      - name: "Setup node"
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: "Install dependencies"
        run: pnpm install

      - name: "Build static site"
        run: pnpm build

      - name: "Setup PHP with PECL extension"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif

      - name: "Download Fastfront CLI"
        run: curl https://fastfront-cli.s3.fr-par.scw.cloud/fastfront-cli.phar -o fastfront-cli.phar

      - name: "Deploy with Fastfront"
        run: php fastfront-cli.phar deploy $FASTFRONT_STAGE ./dist
        env:
          FASTFRONT_STAGE: ${{ github.ref == 'refs/heads/main' && '1b6fa2f5-2471-4045-8a3e-9123d822035d' || '35cb5092-47d9-4c9f-b85f-0438d7e05ef8' }}
          FASTFRONT_API_KEY: ${{ github.ref == 'refs/heads/main' && secrets.FASTFRONT_PROD_API_KEY || secrets.FASTFRONT_STAGING_API_KEY }}
